{{- if .Values.appVault.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-vault
  namespace: {{ .Values.global.mgmt.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: vault
    server: {{ .Values.global.mgmt.address }}
  project: {{ .Values.global.mgmt.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
  source:
    repoURL: {{ default .Values.global.repoURL .Values.appVault.source.repoURL }}
    chart: {{ .Values.appVault.source.chart }}
    targetRevision: {{ .Values.appVault.source.targetRevision }}

    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appVault.values }}
      values: |
        {{- .Values.appVault.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}