{{- if .Values.appTrino.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-jupyter
  namespace: {{ .Values.global.application.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: "{{ .Values.global.namespacePrefix }}-{{ .Values.appTrino.namespace }}"
    server: {{ eq .Values.appTrino.cluster "" | ternary .Values.global.application.address .Values.appTrino.cluster }}
  project: {{ .Values.global.application.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
  source:
    {{- .Values.appTrino.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appTrino.values }}
      values: |
        {{- .Values.appTrino.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}