{{- if .Values.appJupyter.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: {{ .Values.global.application.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: {{ include "teleport.namespace" (dict "Values" .Values "namespace" .Values.appJupyter.namespace) }}
    server: {{ eq .Values.appJupyter.cluster "" | ternary .Values.global.application.address .Values.appJupyter.cluster }}
  project: {{ .Values.global.application.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      name: hub
      jsonPointers:
        - /data/hub.config.CryptKeeper.keys
        - /data/hub.config.JupyterHub.cookie_secret
        - /data/hub.config.ConfigurableHTTPProxy.auth_token
    - group: apps
      kind: Deployment
      name: hub
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
    - group: apps
      kind: Deployment
      name: proxy
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1auth-token
  source:
    {{- .Values.appJupyter.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appJupyter.values }}
      values: |
        {{- .Values.appJupyter.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}