{{- if .Values.appRabbitMQ.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: {{ .Values.global.application.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: {{ include "teleport.namespace" (dict "Values" .Values "namespace" .Values.appRabbitMQ.namespace) }}
    server: {{ eq .Values.appRabbitMQ.cluster "" | ternary .Values.global.application.address .Values.appRabbitMQ.cluster }}
  project: {{ .Values.global.application.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
  source:
    {{- .Values.appRabbitMQ.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appRabbitMQ.values }}
      values: |
        {{- .Values.appRabbitMQ.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}