{{- if .Values.appReloader.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: {{ .Values.global.application.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: {{ include "teleport.namespace" (dict "Values" .Values "namespace" .Values.appReloader.namespace) }}
    # this has to be installed alongside Trino, so we use the Trino cluster values
    server: {{ eq .Values.appTrino.cluster "" | ternary .Values.global.application.address .Values.appTrino.cluster }}
  project: {{ .Values.global.application.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
  source:
    {{- .Values.appReloader.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appReloader.values }}
      values: |
        {{- .Values.appReloader.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}