{{- if .Values.appOpa.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-opa
  namespace: {{ .Values.global.management.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: "{{ .Values.global.namespacePrefix }}-{{ .Values.appOpa.namespace }}"
    server: {{ eq .Values.appOpa.cluster_override "" | ternary .Values.global.management.address .Values.appOpa.cluster_override }}
  project: {{ .Values.global.management.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
  source:
    {{- .Values.appOpa.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appOpa.values }}
      values: |
        {{- .Values.appOpa.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}