{{- if .Values.appPromStack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: {{ .Values.global.monitoring.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: {{ include "teleport.namespace" (dict "Values" .Values "namespace" .Values.appPromStack.namespace) }}
    server: {{ eq .Values.appPromStack.cluster "" | ternary .Values.global.monitoring.address .Values.appPromStack.cluster }}
  project: {{ .Values.global.monitoring.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:  
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    {{- .Values.appPromStack.source | toYaml | nindent 4 }}
    helm:
      valueFiles:
        - values.yaml
      {{- if .Values.appPromStack.values }}
      values: |
        {{- .Values.appPromStack.values | toYaml | nindent 8 }}
      {{- end }}
{{- end }}