---

- set_fact:
    dep_item_new: {}

- set_fact:
    dep_item_new:
      value:
        source:
          chart: "{{ dep_item.chart | trim }}"
          targetRevision: "{{ dep_item.targetRevision | trim }}"
          repoURL: "{{ dep_item.repoURL | trim }}"

- include_tasks: populate_nexus_helm.yml
  vars:
    item: "{{ dep_item_new }}"