---
# Process a single _nexus_repos_global_list for configured formats and apply default values for type.
- name: Process definitions for docker
  block:
    - name: Apply defaults to docker proxy repos
      ansible.builtin.set_fact:
        nexus_repos_docker_proxy: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.proxies.docker -%}
            {{ result.append(_nexus_repos_docker_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Apply defaults to docker group repos
      ansible.builtin.set_fact:
        nexus_repos_docker_group: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.repo_groups.docker -%}
            {{ result.append(_nexus_repos_docker_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Apply defaults to docker hosted repos
      ansible.builtin.set_fact:
        nexus_repos_docker_hosted: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.hosted.docker -%}
            {{ result.append(_nexus_repos_docker_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Add docker repositories to global repos list
      ansible.builtin.set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_docker_proxy | map('combine', {"format": "docker", "type": "proxy"}) | list)
            +
            (nexus_repos_docker_group | map('combine', {"format": "docker", "type": "group"}) | list)
            + 
            (nexus_repos_docker_hosted | map('combine', {"format": "docker", "type": "hosted"}) | list)
          }}

- name: Process definitions for pypi
  block:
    - name: Apply defaults to pypi proxy repos
      ansible.builtin.set_fact:
        nexus_repos_pypi_proxy: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.proxies.pypi -%}
            {{ result.append(_nexus_repos_pypi_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Add pypi repositories to global repos list
      ansible.builtin.set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_pypi_proxy | map('combine', {"format": "pypi", "type": "proxy"}) | list)
          }}

- name: Process definitions for helm repositories
  block:
    - name: Apply defaults to helm proxy repos
      ansible.builtin.set_fact:
        nexus_repos_helm_proxy: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.proxies.helm -%}
            {{ result.append(_nexus_repos_helm_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Apply defaults to helm hosted repos
      ansible.builtin.set_fact:
        nexus_repos_helm_hosted: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.hosted.helm -%}
            {{ result.append(_nexus_repos_helm_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Add helm repositories to global repos list
      ansible.builtin.set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_helm_proxy | map('combine', {"format": "helm", "type": "proxy"}) | list)
            +
            (nexus_repos_helm_hosted | map('combine', {"format": "helm", "type": "hosted"}) | list)
          }}

- name: Process definitions for r
  block:
    - name: Apply defaults to r proxy repos
      ansible.builtin.set_fact:
        nexus_repos_r_proxy: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.proxies.cran -%}
            {{ result.append(_nexus_repos_r_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Add r repositories to global repos list
      ansible.builtin.set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_r_proxy | map('combine', {"format": "r", "type": "proxy"}) | list)
          }}

- name: Process definitions for conda
  block:
    - name: Apply defaults to conda proxy repos
      ansible.builtin.set_fact:
        nexus_repos_conda_proxy: >-
          {%- set result = [] -%}
          {%- for repo in nexus_config.proxies.conda -%}
            {{ result.append(_nexus_repos_r_defaults | combine(repo)) }}
          {%- endfor -%}
          {{ result | to_json | from_json }}

    - name: Add conda repositories to global repos list
      ansible.builtin.set_fact:
        _nexus_repos_global_list: >-
          {{
            _nexus_repos_global_list | default([])
            +
            (nexus_repos_conda_proxy | map('combine', {"format": "conda", "type": "proxy"}) | list)
          }}