---

# in charts/teleport/values.yaml, get all helm sources
- set_fact:
    app_helm_sources: "{{ lookup('file', '{{ teleport_chart_directory }}/values.yaml') | from_yaml }}"

# for each source
- name: get all helm charts, and upload them to nexus
  include_tasks: populate_nexus_helm.yml
  loop: "{{ app_helm_sources.keys() | reject('search', 'global') }}"