
global:
  namespacePrefix: dare
  application:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default
  management:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default
  monitoring:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default

appGuacamole:
  enabled: true
  cluster: ""
  namespace: guacamole
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: guacamole
    # renovate: datasource=helm depName=guacamole registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.0.2

appJupyter:
  enabled: true
  cluster: ""
  namespace: jupyter
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: jupyter
    # renovate: datasource=helm depName=jupyter registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.0.0

appTrino:
  enabled: true
  cluster: ""
  namespace: trino
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: trino
    # renovate: datasource=helm depName=trino registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.1.1

appHive:
  enabled: true
  cluster: ""
  namespace: hive
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: hive
    # renovate: datasource=helm depName=hive registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.2.0

appMinioTenant:
  enabled: true
  cluster: ""
  namespace: minio-tenant
  source:
    repoURL: https://operator.min.io/
    chart: tenant
    # renovate: datasource=helm depName=tenant registryUrl=https://operator.min.io/
    targetRevision: 5.0.6

appVault:
  enabled: true
  cluster: ""
  namespace: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    # renovate: datasource=helm depName=vault registryUrl=https://helm.releases.hashicorp.com
    targetRevision: 0.24.1

appOpa:
  enabled: true
  cluster: ""
  namespace: opa
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: opa
    # renovate: datasource=helm depName=opa registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.0.0

appControl:
  enabled: true
  cluster: ""
  namespace: control
  source:
    repoURL: https://harbor.ukserp.ac.uk/chartrepo/dare
    chart: control
    # renovate: datasource=helm depName=control registryUrl=https://harbor.ukserp.ac.uk/chartrepo/dare
    targetRevision: 1.1.0

appKeycloak:
  enabled: true
  cluster: ""
  namespace: keycloak
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    # renovate: datasource=helm depName=keycloak registryUrl=https://charts.bitnami.com/bitnami
    targetRevision: 15.1.6

appPromStack:
  enabled: true
  cluster: ""
  namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    # renovate: datasource=helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    targetRevision: 49.2.0

appLoki:
  enabled: true
  cluster: ""
  namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    # renovate: datasource=helm depName=loki-stack registryUrl=https://grafana.github.io/helm-charts
    targetRevision: 2.9.10
  values:
    loki:
      isDefault: false
