global:
  namespacePrefix: dare
  application:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default
  management:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default
  monitoring:
    address: https://kubernetes.default.svc
    argocd:
      namespace: argocd
      project: default

appRabbitMQ:
  enabled: true
  cluster: ""
  namespace: rabbitmq
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    # renovate: datasource=helm depName=rabbitmq registryUrl=https://charts.bitnami.com/bitnami
    targetRevision: 11.13.0

appAirflow:
  enabled: true
  cluster: ""
  namespace: airflow
  source:
    repoURL: https://airflow-helm.github.io/charts
    chart: airflow
    # renovate: datasource=helm depName=airflow registryUrl=https://airflow-helm.github.io/charts
    targetRevision: 8.7.1
  values:
    airflow:
      image:
        repository: harbor.ukserp.ac.uk/dare/airflow/base
        tag: 1.1.7

appGuacamole:
  enabled: false
  cluster: ""
  namespace: guacamole
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: guacamole
    # renovate: datasource=docker depName=dare/chart/guacamole registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.6.11

appJupyter:
  enabled: true
  cluster: ""
  namespace: jupyter
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: jupyter
    # renovate: datasource=docker depName=dare/chart/jupyter registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.3.8

appTrino:
  enabled: true
  cluster: ""
  namespace: trino
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: trino
    # renovate: datasource=docker depName=dare/chart/trino registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.7.13

appHive:
  enabled: true
  cluster: ""
  namespace: hive
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: hive
    # renovate: datasource=docker depName=dare/chart/hive registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.6.1

appReloader:
  enabled: true
  # this needs to be installed alongside Trino, so it uses the Trino cluster value
  namespace: reloader
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    # renovate: datasource=helm depName=reloader registryUrl=https://stakater.github.io/stakater-charts
    targetRevision: 1.0.43

appMinioTenant:
  enabled: true
  cluster: ""
  namespace: minio-tenant
  source:
    repoURL: https://operator.min.io/
    chart: tenant
    # renovate: datasource=helm depName=tenant registryUrl=https://operator.min.io/
    targetRevision: 5.0.6

appVault:
  enabled: true
  cluster: ""
  namespace: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    # renovate: datasource=helm depName=vault registryUrl=https://helm.releases.hashicorp.com
    targetRevision: 0.27.0

appOpa:
  enabled: true
  cluster: ""
  namespace: opa
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: opa
    # renovate: datasource=docker depName=dare/chart/opa registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.5.6

appControl:
  enabled: false
  cluster: ""
  namespace: control
  source:
    repoURL: harbor.ukserp.ac.uk/dare/chart
    chart: control
    # renovate: datasource=docker depName=dare-trefx/chart/control registryUrl=https://harbor.ukserp.ac.uk
    targetRevision: 1.28.4

appKeycloak:
  enabled: true
  cluster: ""
  namespace: keycloak
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    # renovate: datasource=helm depName=keycloak registryUrl=https://charts.bitnami.com/bitnami
    targetRevision: 15.1.6

appPromStack:
  enabled: true
  cluster: ""
  namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    # renovate: datasource=helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    targetRevision: 46.3.0

appLoki:
  enabled: true
  cluster: ""
  namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    # renovate: datasource=helm depName=loki-stack registryUrl=https://grafana.github.io/helm-charts
    targetRevision: 2.9.10
  values:
    loki:
      isDefault: false
