---

- name: get path to kubeconfig file
  set_fact: 
    kubeconfig_dir: "{{ item.value }}"
  loop: "{{ k3s_server_environment }}"
  when: 
    - item.key == 'KUBECONFIG'

- name: get all vault pods in vault namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ vault_namespace }}"
    label_selectors:
      - "app.kubernetes.io/instance={{ vault_install_name }}"
      - "app.kubernetes.io/name=vault"
    kubeconfig: "{{ kubeconfig_dir }}"
  register: vault_pods_spec

- set_fact:
    vault_pods: "{{ vault_pods | default([]) + [ item.metadata.name ] }}"
  with_items: "{{ vault_pods_spec.resources }}"

- name: initialise vault with given number of key shares and threshold
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_namespace }}"
    pod: "{{ vault_pods[0] }}"
    command: "vault operator init -key-shares={{ vault_number_key_shares }} -key-threshold={{ vault_key_threshold }} -format=json"
  register: vault_init_result