---
- set_fact:
    policy_name: "{{ policy_file.path | basename | splitext | first }}"
    policy_content: "{{ lookup('file', '{{ policy_file.path }}') }}"

- name: apply policy to vault
  command: kubectl exec -i --tty=false {{ vault_pods[0] }} -n {{ vault_namespace }} -- vault policy write {{ policy_name }} -
  args:
    stdin: "{{ policy_content }}"