micro_cluster:
  vars:
    k3s_deploy_rookceph: false
    k3s_deploy_metallb: false
    k3s_deploy_opa: true
    k3s_deploy_argo: true
    k3s_deploy_postop: true
    k3s_deploy_nexus: true
    k3s_deploy_minioop: true

    k3s_server_environment:
    - key: KUBECONFIG
      value: '/root/.kube/config'

  hosts:
    single_instance:
      ansible_host: 10.211.55.8
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      k3s_lead_control_node: true

