---

- include_tasks: repos.yml
  loop: "{{ repos }}"

# make the cluster secrets
- include_tasks: clusters.yml
  loop: "{{ clusters }}"

- name: deploy the teleport chart!
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/app-watcher.j2"