---

# make the repo secrets
- name: make helm repo secret
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/argocd-helm-repo.yml.j2"
  when: item.type == "helm"

- name: make git repo secret
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/argocd-git-repo.j2"
  when: item.type == "git"
