name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  changes:
    # Detect which files have been changed on this PR's full history 
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes-release.yaml@v5.0.3
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        chart:
          - './.github/workflows/on-release.yaml'
          - 'charts/teleport/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
      
  chart:
    # Build the chart and push it as x.y.z-rc
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-chart.yaml@v5.0.3
    with:
      job-name: chart
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: ${{ vars.HARBOR_REPO }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/teleport
      test-command: |
        helm template $CHART --values charts/teleport/values.yaml
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
